# Generated by Django 3.0.6 on 2020-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_text', models.TextField()),
                ('photo', models.ImageField(upload_to='cars')),
                ('url', models.URLField(max_length=250)),
            ],
        ),
    ]
