# Generated by Django 3.0.7 on 2020-06-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='card_text',
            field=models.TextField(),
        ),
    ]
