# Generated by Django 3.0.7 on 2020-06-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytsite', '0003_auto_20200613_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_submission',
            name='photo',
            field=models.ImageField(upload_to='cars'),
        ),
    ]
